config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Index, LoginStatus
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    # 웰컴 페이지(index)에 로그인 버튼 클릭시 login_statue 실행 후, 결과에 따라 페이지 이동
    path('login_status/', LoginStatus.as_view(), name='login_status'),
    # 모델, 폼, 템플릿에서 markdown을 사용하기 위해 설정
    path('markdownx/', include('markdownx.urls')),
    path('users/', include('myapps.users.users_urls')),
    path('posts/', include('myapps.posts.posts_urls')),
    path('feeds/', include('myapps.feeds.feeds_urls')),
    path('ai_data/', include('myapps.ai_data.ai_data_urls')),
    path('common/', include('myapps.common.common_urls')),
]

# 저장된 이미지를 불러오기 위한 설정
urlpatterns += static(
    settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

myapps/common/models.py
from django.db import models

# Create your models here.

# 유저의 기본 메인 페이지 조회 및 변경을 위해 IntegerChoices로 재사용 가능한 선택 목록 정의
class DefaultMainPageChoices(models.IntegerChoices):
    OPTION_ZERO = 0, 'Grobo(포털 페이지)'
    OPTION_ONE = 1, 'Grobat(플랫폼 페이지)'

myapps/feeds/models.py
from django.db import models

# Create your models here.

class Feed(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    context = models.TextField("내용", blank=True)
    created = models.DateTimeField("작성일시", auto_now_add=True)
    
    tag = models.ManyToManyField("feeds.HashTag", verbose_name="태그명", related_name="tag_feeds")
    
class FeedImage(models.Model):
    feed = models.ForeignKey("Feed", verbose_name="피드", on_delete=models.CASCADE)
    image_url = models.ImageField("피드 이미지", upload_to="feed/image", blank=False, null=False)    

class FeedComment(models.Model):
    user = models.ForeignKey(
        "users.User", 
        verbose_name="작성자", 
        on_delete=models.CASCADE,
        )
    feed = models.ForeignKey(
        "Feed", 
        verbose_name="피드", 
        on_delete=models.CASCADE,
        )
    comment = models.TextField("댓글", blank=False, null=False)
    created = models.DateTimeField("작성일시", auto_now_add=True)
    
class HashTag(models.Model):
    tag_name = models.CharField("태그명", max_length=50)
    
    def __str__(self):
        return self.tag_name

myapps/posts/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.widgets import MarkdownxWidget

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    title = models.CharField("제목", max_length=255, blank=False, null=False)
    content = MarkdownxField("내용", blank=True, null=True)
    created = models.DateTimeField("생성일시", auto_now_add=True)
    
    tag = models.ManyToManyField("feeds.HashTag", verbose_name="태그명", related_name="tag_posts", blank=True)
    
    def __str__(self):
        return self.title
    
# 미리보기 포스트 이미지와 완성된 포스트 이미지를 갖는 테이블(유연한 ForeignKey 전환을 위해 2개의 키를 할당)
class PostImage(models.Model):
    post = models.ForeignKey("Post", verbose_name='포스트 이미지', blank=True, null=True, on_delete=models.CASCADE)
    # preview_post랑 연결된 'PreviewPost' 객체가 삭제될 때, 이미지가 같이 삭제되지 않고 None 로 바뀌게 설정('PreviewPost' 객체는 사용자가 포스트 저장시 자동 삭제될 예정)
    preview_post = models.ForeignKey('PreviewPost', verbose_name='미리보기 이미지', blank=True, null=True, on_delete=models.SET_NULL)
    image_url = models.ImageField("포스트 이미지", upload_to="post/image", blank=True, null=True)
    
class PostComment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        "Post",
        verbose_name="포스트",
        on_delete=models.CASCADE,
        )
    comment = models.TextField("댓글")
    created = models.DateTimeField("작성일시", auto_now_add=True)

# 포스트 미리보기용 데이터 테이블(임시 보관용 테이블)
class PreviewPost(models.Model):
    user = models.ForeignKey('users.User', verbose_name='작성자', on_delete=models.CASCADE)
    title = models.CharField('제목', max_length=255, blank=True, null=True)
    content = MarkdownxField('내용', blank=True, null=True)
    tag = models.CharField('태그', max_length=255, blank=True, null=True)
    created = models.DateTimeField('생성일시', auto_now_add=True)
    
# 검색 키워드 데이터 테이블(User 모델과 다대다 관계에서 유저 모델에서만 키워드를 추적할 수 있게 연결되어 있음. / symmetrical=False)
class SearchKeyword(models.Model):
    keyword = models.CharField('검색 키워드', max_length=50)
    # blank=True로 초기 인스턴스 또는 키워드 1개 인스턴스 생성 시, 무한 생성 요청 해결
    keyword_relation = models.ManyToManyField('self', verbose_name='연관 키워드', symmetrical=True, blank=True)
    count = models.IntegerField('검색 횟수', default=1)
    
    def __str__(self):
        return self.keyword
    
    class Meta:
        ordering = ['-count'] # 가장 많이 검색된 키워드를 우선적으로 가져오기 위해 내림차순으로 설정

myapps/ai_data/views.py
from django.shortcuts import render
from django.views import generic
from .models import AiQuestion, AiAnswer

# Create your views here.

class AiMain(generic.ListView):
    template_name = 'ai_data/ai_main.html'
    model = AiQuestion
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['test'] = 'AiMain view 테스트용'
        return context

myapps/common/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.urls import resolve, reverse
from urllib.parse import urlparse
from django.contrib.auth import authenticate

# Create your views here.

class PageSwitching(View):
    def post(self, request):
        # 템플릿에서 받은 current_url = 전체 주소(예: http://example.com/posts/posts_main/)
        current_url = request.POST.get('current_url', '')
        # 전체 주소를 urlparse() 함수를 사용하여, 전체 주소를 구분하여 받을 수 있도록 선 작업
        parsed_url = urlparse(current_url)
        # urlparse()함수 기능인 경로 부분만을 추출하는 path로 URL 경로만 추출 (예: '/posts/posts_main/')
        # 아래 resolve()함수를 통해 URL패턴과 비교하려면 URL 경로 맨 앞에 '/' 포함된 URL 경로가 필요 (조건문으로 '/'가 없을 경우 포함되도록 작업 )
        path = parsed_url.path if parsed_url.path.startswith('/') else '/' + parsed_url.path
        # resolve 속성 중 하나인 'namespace'로, 입력된 URL경로를 가지고 있는 app_name을 반환하는 속성이다.
        app_name = resolve(path).namespace
        
        # 가져온 app_name에 따라 redirect 값을 지정
        if app_name == 'posts':
            return redirect('feeds:feeds_main')
        elif app_name == 'feeds':
            return redirect('posts:posts_main')
        else:
            # 중립 페이지의 경우, 유저의 기본 메인 페이지로 이동
            user_main_page = request.user.default_main_page # 유저의 기본 메인 페이지 값 가져오기
            if user_main_page == 0:
                return redirect('posts:posts_main')
            else:
                return redirect('feeds:feeds_main')
            
# 유저 로그인 여부에 따른 버튼 변환
def user_authenticated(user):
    if user.is_authenticated:
        return "Logout", reverse('users:logout'), True
    else:
        return "Login", reverse('users:login'), False     

myapps/feeds/views.py
from django.shortcuts import render
from django.views import generic
from .models import Feed, FeedComment

# Create your views here.

class Platform_main(generic.ListView):
    template_name = 'feeds/platform_main.html'
    model = Feed
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['test'] = 'Platform_main view 테스트용'
        return context

myapps/posts/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import resolve, reverse_lazy, reverse
from django.views import generic, View

from .models import Post, PostImage, PostComment, PreviewPost, SearchKeyword
from .naver_api import NaverSearchAPI, text_transform, TextKeywordReader, Keyword_save
from myapps.users.models import UserSearchKeyword
from myapps.feeds.models import HashTag
from myapps.posts.models import Post
from myapps.common.views import user_authenticated
from myapps.form.posts.post_form import PostCustomEditorForm, PostCommentForm
from myapps.form.custom_form import validate_image

from markdownx.utils import markdownify

import time
import asyncio

# Create your views here.

# 포털 사이트 메인 페이지를 로드하는 뷰(검색 키워드 상위 3개와 관련된 데이터륿 보여주는 알고리즘 포함)
class PortalMainAPI(generic.TemplateView):
    template_name = 'posts/portal_main.html'
    
    def get_context_data(self, **kwargs):
        # 부모 클래스인 'TemplateView'에 내장되어 있고 템플릿에 데이터를 담당하는 'get_context_data()'메서드를 호출하여 데이터를 추가
        context = super().get_context_data(**kwargs) 
        
        algorithms_api_format = NaverSearchAPI()
        algorithms_data_list = algorithms_api_format.algorithms_api_request(self.request.user)
        context['news_data_list'] = algorithms_data_list['news']
        context['shop_data_list'] = algorithms_data_list['shop']
        context['blog_data_list'] = algorithms_data_list['blog']
        
        login_button_text, login_button_url, login_yn = user_authenticated(self.request.user)
        
        keyword_match_post_format = GetPostMatchKeyword()
        post_list, result_text, result_bool = keyword_match_post_format.user_keyword_match_post(self.request.user)
            
        context['login_button_text'] = login_button_text
        context['login_button_url'] = login_button_url
        context['text'] = "환영합니다. 포털 메인 페이지입니다."
        return context

# 포털 검색 결과 페이지
class PortalSearchResults(generic.TemplateView):
    template_name = 'posts/portal_search_results.html'
    
    # 검색어 처리 진행
    def get_context_data(self, **kwargs):
        # 부모 클래스인 'TemplateView'에 내장되어 있고 템플릿에 데이터를 담당하는 'get_context_data()'메서드를 호출하여 데이터를 추가
        context = super().get_context_data(**kwargs)
        
        text = self.request.GET.get('portal_search_text', '') # 검색 창에 입력된 텍스트 데이터를 가져와서 할당
        
        text_reader_format = TextKeywordReader(text) # TextKeywordReader 클래스의 포맷 인스턴스 생성
        keyword_list = text_reader_format.text_keyword_reader() # 텍스트에서 키워드를 추출하는 전처리 메서드 실행하고, 결과를 keyword_list를 변수에 할당
        
        keyword_save_format = Keyword_save(self.request.user, keyword_list) # Keyword_save 클래스의 포맷 인스턴스 생성
        keyword_save_format.keyword_save() # keyword를 저장하는 메서드 실행
        
        # transformed_text = text_transform(text) # API url용 문자열로 변환(공백을 '+'로 변환)
        
        search_api_format = NaverSearchAPI()
        search_results = search_api_format.search_api_request(text)
        
        # news_results = data_thumbnail_extraction(search_results['news']) # 뉴스 데이터만 추출
        # webkr_results = data_thumbnail_extraction(search_results['webkr']) # 웹문서 데이터만 추출
        
        context['news_data_list'] = search_results['news']
        context['webkr_data_list'] = search_results['webkr']
        context['encyc_data_list'] = search_results['encyc']
        
        # 직접 만든 '유저 로그인 여부에 따라 버튼명과 연결 주소 그리고 로그인 여부'를 반환하는 함수
        login_button_text, login_button_url, login_yn = user_authenticated(self.request.user)
        context['login_button_text'] = login_button_text # nav태그에 들어가는 요소(로그인 여부에 따른 동적 버튼)
        context['login_button_url'] = login_button_url # nav태그에 들어가는 요소(로그인 여부에 따른 동적 버튼)
        context['text'] = '환영합니다. 포털 검색 결과 페이지입니다.'
        
        return context

# 포스트 디테일 페이지 보여주는 뷰
class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/posts_detail.html'
    context_object_name = 'object'

# 포스트 생성 페이지를 보여주는 뷰
class MarkdownEditorView(generic.FormView):
    form_class = PostCustomEditorForm
    template_name = 'posts/posts_add.html'
    
    # 사용자 로그인 여부에 따른 동적으로 페이지 로드
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:login') # 로그인 상태가 아니면, 로그인 페이지로 이동
        else:
            # super()로 부모 클래스'FormView'의 get메서드를 재호출해서 자식 클래스(내가 정의한 클래스: form_class, template_name를 적용한다.)
            return super().get(request, *args, **kwargs)

# 실시간 미리보기 기능 구현 뷰(템플릿에서 온 Ajax 요청을 처리하는 뷰)
class PostPreview(View):
    http_method_names = ['post'] # 뷰가 POST 요청만 받게 설정
    
    def post(self, request):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            title = request.POST.get('title', '')
            markdown_text = request.POST.get('markdown_text', '')
            tag = request.POST.get('tag', '')
            html_preview = markdownify(markdown_text)
            
            return JsonResponse({
                'title': title,
                'html_preview': html_preview,
                'tag': tag,
                })
            
        return JsonResponse({'error':"실시간 미리보기 기능의 요청이 XML 방식의 요청이 아닙니다."}, status=400)
    
# 포스트 생성 페이지에 이미지를 첨부시 반환하는 뷰
class PostImageUpload(View):
    http_method_names = ['post'] # 뷰가 POST 요청만 받게 설정
    
    def post(self, request):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest': # 스크립트에서 .ajax로 데이터를 뷰로 보내면, 해당 요청 헤드에는 HTTP가 'XMLHttpRequest'로 들어감
            user = request.user # 요청을 보낸 요청자의 user 데이터 가져오기
            markdown_text = request.POST.get('content','')
            images_data = request.FILES.getlist('post_images_upload_field')
            
            # 사용자가 이미지 업로드가 처음인 경우
            if not PreviewPost.objects.filter(user=user).exists(): # .exists()함수는 테이블에 해당 레코드의 존재 여부를 bool 형식으로 반환
                first_post = True # 첫 이미지 업로드 시, 임시post 레코드 생성을 위해 'True'로 설정
                first_upload = True # 첫 이미지 업로드 시, 임시image 레코드 생성을 위해 'True'로 설정
                preview_post = self.preview_post_save(user, markdown_text, first_post) # markdown_text 데이터를 테이블에 저장하고 텍스트 형식으로 반환하는 메서드
                preview_content = preview_post.content # 함수 실행 결과인 'preview_post'레코드 객체에서 'content'속성의 값만 호출하여 변수에 할당
                post_content = preview_post.content # 함수 실행 결과인 'preview_post'레코드 객체에서 'content'속성의 값만 호출하여 변수에 할당
                
                # 이미지를 저장하는 과정에서 유효성 검사도 같이 진행한다.
                is_valid, error_message = self.preview_image_save(preview_post, images_data, first_upload) # 키-값 쌍 배열의 이미지 파일을 테이블에 저장하고 파일 url 형식으로 반환하는 메서드

                # 이미지 파일의 유효성 검사가 False인 경우, 유효성 검사 함수에서 반환된 오류 메세지를 넣어서 반환
                if is_valid == False:
                    return JsonResponse({'error': error_message}, status=400)
                
                for image in PostImage.objects.filter(preview_post=preview_post):
                    image_url = image.image_url.url # .url : 해당 이미지 객체를 호출인 가능한 형태의 url로 반환해주는 기능
                    preview_content += f'<br/> ![{image.id}번째 이미지]({image_url})' # 여러 이미지가 새로 방향으로 나열되기 위해 '<br/>'를 추가
                    post_content += f'\n<br/> ![{image.id}번째 이미지]({image_url})' # post_content 변수는 마크다운 필드에 들어갈 값으로 '문장'의 줄바꿈을 위해 '텍스트 필드'의 줄바꿈 키워드인 '/n'을 추가
            
            # 사용자가 이미지 업로드가 두 번 이상인 경우
            else:
                first_post = False # 두 번째 또는 그 이상 이미지 업로드 시, 기존 임시post 레코드를 가져오기 위해 'False'로 설정
                first_upload = False # 두 번째 또는 그 이상 이미지 업로드 시, 기존 임시image 레코드를 가져오기 위해 'False'로 설정
                preview_post = self.preview_post_save(user, markdown_text, first_post)
                preview_content = preview_post.content
                post_content = preview_post.content
                
                is_valid, preview_image_id = self.preview_image_save(preview_post, images_data, first_upload)
                
                if is_valid == False:
                    return JsonResponse({'error': preview_image_id}, status=400)

                for id in preview_image_id:
                    image_objects = PostImage.objects.get(id=id)
                    image_url = image_objects.image_url.url
                    preview_content += f'<br/> ![{id}번째 이미지]({image_url})'
                    post_content += f'\n<br/> ![{id}번째 이미지]({image_url})'
            
            markdown_html = markdownify(preview_content)     
            return JsonResponse({'markdown_text': post_content, 'html_preview': markdown_html,})
            
        return JsonResponse({'error': "이미지 첨부 상식의 요청이 XML 방식의 요청이 아닙니다."}, status=400)
    
    def preview_post_save(self, user, markdown_text, first_post):
        if first_post == True: # 신규 작성인 경우, 임시 테이블에 신규 임시post 레코드 생성
            preview_post = PreviewPost.objects.create(user=user, content = markdown_text)
        else: # 추가 작성인 경우, 기존에 있던 임시 post 레코드 호출 및 내용(content 속성) 업데이트
            preview_post = PreviewPost.objects.filter(user=user).first()
            if preview_post:
                preview_post.content = markdown_text
                preview_post.save()
            
        return preview_post # 저장된 markdown_text를 텍스트 데이터 형식으로 반환
        
    def preview_image_save(self, preview_post, images_data, first_upload):
        if first_upload == True:
            for image in images_data:
                is_valid, error_message = validate_image(image)
                if is_valid:
                    PostImage.objects.create(preview_post = preview_post, image_url = image)
                else:
                    return False, error_message
                
            return True, None
            
        else:
            preview_image_id = [] # 새로 추가될 이미지 id 저장을 위한 리스트 변수 선언
            for image in images_data:
                is_valid, error_message = validate_image(image)
                if is_valid:
                    preview_image = PostImage.objects.create(preview_post = preview_post, image_url = image)

myapps/templates/posts/portal_search_results.html
{% extends 'base/portal_nav.html' %}
{% load static %}

{% block css %}{% endblock %}

{% block content %}
    <h1>검색 결과 페이지</h1>
    <!-- 탑 영어 -->
    <div id="portal_search_top" class="portal-search-results-top">
        <span>Grobo</span>
        <form id="portal_search_results_box" class="portal-search-results-box" method="get">
            <input id="portal_search_results_input" class="portal-search-results-input" name="portal_search_text" type="text">
            <button id="portal_search_results_button" class="portal-search-results-button" type="submit">검색</button>
        </form>
    </div>
    <!-- 메인 영역 -->
    <div id="portal_search_main" class="portal-search-main">
        <h1>검색 페이지 메인</h1>
        {{ text }}
    </div>
    <!-- 사이드 영역(오른쪽) -->
    <div id="portal_aside" class="portal-aside">
        <h1>사이드 영역</h1>
        <!-- 추후 관련 검색어 표시 요소 삽입 -->
    </div>
{% endblock %}
{% block footer %}
    <!-- 푸터 영역 -->
    <div id="portal_footer" class="portal-footer">
        <h1>포털 푸터</h1>
    </div>
{% endblock %}

{% block js %} {% endblock %}

myapps/templates/posts/posts_add copy.html
{% extends 'base/base_nav.html' %}

{% block content %}
    <h1>Post 생성 페이지</h1>
    <form id="posts_images_upload" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <input id="id_images_upload" name="images_upload" type="file" multiple><br>
        <button type="submit" id="image_submit">이미지 첨부</button>
    </form>
    <form id="posts_add" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <!-- {{ form.as_p }} 
        <button type="submit">글 작성</button> -->
        <ul>
            <li>
                <label for="id_title">제목:</label>
                <input type="text" id="id_title" name="title">
            </li>
            <li>
                <label for="id_context">내용:</label>
                <textarea id="id_context" name="context"></textarea>
            </li>
            <li>
                <label for="id_tag">태그:</label>
                <input type="text" id="id_tag" name="tag">
            </li>
            <li>
                <button type="submit" id="form_submit">글 작성</button>
            </li>
        </ul>
    </form>
{% endblock %}
{% block js %}
<script>
    // 페이지가 모두 로드되면 해당 이벤트 실행 준비
    document.addEventListener('DOMContentLoaded', function () {
        // 'image_submit'을 id로 하는 버튼을 '클릭'시, 이벤트(작업) 실행
        document.getElementById('image_submit').addEventListener('click', function (event) {
            event.preventDefault();
            // 'posts_images_upload'를 id로 하는 폼에서 생성된 폼 데이터를 저장
            var imageData = new FormData(document.getElementById('posts_images_upload'));
            // 'posts_add'를 id로 하는 폼의 폼 필드를 저장
            var formData = new FormData(document.getElementById('posts_add'))
            // 각 폼의 필드에 맞는 데이터 저장
            formData.append('title', formData.get('title'));
            formData.append('context', formData.get('context'));
            formData.append('tag', formData.get('tag'));

            // 이미지 첨부 폼의 데이터를 글 작성 폼 데이터에 추가
            // 본래 FormData는 키-값 형태의 객체이다.
            // entries()를 사용하여 키-값 객체를 쉽게 꺼낼 수 있게 튜플로 만든다.
            // postData.append(pair[0], pair[1]) : 각각 pair[0]에는 키 , pair[0] 값을 넣는다.
            var i = 0;
            for (var pair of imageData.entries()) {
                // 이미지 파일의 이름을 고유하게 설정하여 FormData에 추가
                formData.append('image' + i, pair[1]);
                i += 2; // 키 값을 2씩 증가하여 고유한 키 생성
            }

            // 결합된 데이터들을 서버에 보내주는 함수 실행
            sendDataToServer(formData);
        });
    });
    
    // 받은 데이터를 서버에 보내주는 함수
    function sendDataToServer(formData) {
        fetch("{% url 'posts:posts_images_upload' %}", {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': "{{ csrf_token }}" // CSRF 토큰을 설정해야 합니다.
            }
        })
        // fetch에서 반환된 응답 처리
        // HTTP 응답(response)의 내용을 JSON 형식으로 파싱한다.
        // json() : JSON형식의 문자열을 JavaScript객체로 파싱한다.
        // 즉, 서버로부터 받은 JSON 데이터를 JavaScript 객체로 변환하여 다음 Promise로 전달한다.
        .then(response => response.json())

        // response.json()로 파싱된 자바스크립트 객체를 data 변수에 '자동'으로 할당하여 해당 변수로 호출할 수 있게한다.
        .then(data => {
            // 해당 id를 가지고 있는 폼 필드에 해당 데이터 입력
            document.getElementById('id_title').value = data.title;
            document.getElementById('id_context').value = data.context;
            document.getElementById('id_tag').value = data.tag;
        })
        // 서버로 전송에 오류가 있을 경우, 오류 출력
        .catch(error => {
            console.error('Error:', error);
        });
    }
</script>
{% endblock %}

<!-- 두 번째 방식(이미지 전송 버튼과 폼 데이터 전송 버튼이 따로 움직인다.)

document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('image_submit').addEventListener('click', function (event) {
        event.preventDefault();
        var formDataA = new FormData(document.getElementById('posts_images_upload'));
        sendDataToServer(formDataA);
    });

    document.getElementById('submit_b').addEventListener('click', function (event) {
        event.preventDefault();
        var formDataA = new FormData(document.getElementById('a_form'));
        var formDataB = new FormData(document.getElementById('b_form'));
        formDataB.append('title', formDataA.get('title'));
        formDataB.append('content', formDataA.get('content'));
        formDataB.append('tag', formDataA.get('tag'));
        sendDataToServer(formDataB);
    });
});

function sendDataToServer(formData) {
    fetch("{% url 'posts:posts_images_upload' %}", {
        method: 'POST',
        body: formData,
        headers: {
            'X-CSRFToken': "{{ csrf_token }}" // CSRF 토큰을 설정해야 합니다.
        }
    })
    .then(response => response.text())
    .then(data => {
        document.getElementById('result').innerHTML = data; // 서버에서 받은 데이터를 결과 영역에 표시합니다.
    })
    .catch(error => {
        console.error('Error:', error);
    });
} -->

<!-- 첫 번째 방식(서버로 데이터가 전송은 가능하나, 서버에서 템플릿으로 데이터 전송 불가능) -->
    <!-- // 이미지 첨부 폼과 글 작성 폼의 데이터를 모두 수집하여 서버로 전송하는 함수
    function submitForms() {
        // 이미지 첨부 폼과 글 작성 폼의 데이터를 수집
        var imageData = new FormData(document.getElementById("posts_images_upload"));
        var postData = new FormData(document.getElementById("posts_add"));

        // 이미지 첨부 폼의 데이터를 글 작성 폼 데이터에 추가
        // 본래 FormData는 키-값 형태의 객체이다.
        // entries()를 사용하여 키-값 객체를 쉽게 꺼낼 수 있게 튜플로 만든다.
        // postData.append(pair[0], pair[1]) : 각각 pair[0]에는 키 , pair[0] 값을 넣는다.
        var i = 0;
        for (var pair of imageData.entries()) {
            // 이미지 파일의 이름을 고유하게 설정하여 FormData에 추가
            postData.append('image' + i, pair[1]);
            i += 2; // 키 값을 2씩 증가하여 고유한 키 생성
        }

        // 서버로 데이터를 전송(응답 데이터도 해당 주소와 연결된 뷰에서 반환하는 값이다.)
        fetch("{% url 'posts:posts_images_upload' %}", {
            method: "POST",
            body: postData,
            headers: {
                "X-CSRFToken": "{{ csrf_token }}",
            }
        })
    } -->

myapps/templates/posts/posts_detail.html
{% extends 'base/base_nav.html' %}
{% load static %}
{% load posts_filters %}

{% block content %}
    <h1>Post Detail</h1>
    <h2>{{ object.title }}</h2>
    <p>{{ object.content|formatted_markdown }} </p>
    <p>Tags:</p>
    <div>
        {% for tag in object.tag.all %}
            <span>#{{ tag }}</span>
        {% endfor %}
    </div>
{% endblock %}